name: FoesPlugin
main: net.uniloftsky.nukkit.foes.PluginMainKt
version: "${pom.version}"
api: [ "1.0.0" ]
author: uniloftsky
description: Foes plugin to define area where foes will be spawned. Type and amount of foes can be specified as well